#!/bin/sh
# Example from section 4.2 "Other filters"
# From the text:
# "... consider the following pipeline, which prints the 10 most
# frequent words in its input:"

cat $* | tr -sc A-Za-z '\012' | sort | uniq -c | sort -n | tail

# The last command, `5`,  was left off because it doesn't exist on the test 
# system. If this comes from the text, it was not added yet because the
# text code and exercises were entered out-of-order.
