#!/bin/sh
# watchwho:  watch who logs in and out
# Exercise 5-11:  use 'comm' instead of awk to display update

PATH=/bin:/usr/bin
new=/tmp/wwho1.$$
old=/tmp/wwho2.$$
>$old           # create an empty file

while :         # loop forever
do
    who >$new
    comm $old $new 2>/dev/null | awk -F'\t' 'NF == 1 { print "out:     " $1}
                                             NF == 2 { print "in:      " $2}'
    mv $new $old
    sleep 10
done

