#!/bin/sh

trap "" 1 15
if test -t 2>&1
then
    echo "Sending output to 'nohub.out'"
    echo "Sending erro to 'nohub.err'"
    exec nice -5 $* >>nohup.out 2>>nohup.err
else
    exec nice -5 $* 2>&1
fi
