#!/bin/sh
# watchwho:  watch who logs in and out
# requires the 'gawk' version of 'awk', or something that handles unbuffered
# input by default, which 'mawk' does not:
# https://github.com/ThomasDickey/original-mawk/issues/41

PATH=/bin:/usr/bin
new=/tmp/wwho1.$$
old=/tmp/wwho2.$$
>$old           # create an empty file

while :         # loop forever
do
    who >$new
    diff $old $new
    mv $new $old
    sleep 10
done | gawk '/>/ { $1 = "in:      "; print }
            /</ { $1 = "out:     "; print }'
