#!/bin/sh
# watchwho:  watch who logs in and out
# this does not work on the test system: Ubuntu 20.04, no output appears.
# apparently the shell does not like piping the output of the while loop
# into the next command, in this case, 'awk'. not sure why, still looking
# into it. for the workaround, see watchwho2.

PATH=/bin:/usr/bin
new=/tmp/wwho1.$$
old=/tmp/wwho2.$$
>$old           # create an empty file

while :         # loop forever
do
    who >$new
    diff $old $new
    mv $new $old
    sleep 60
done | awk '/>/ { $1 = "in:      "; print }
            /</ { $1 = "out:     "; print }'
